In [3]:
import pandas as pd
Data =[ 15,21,29,21,15,24,32,21,15,30] 
dt= pd.Series(Data)
print("Mean: ",dt.mean())
print("Median: ",dt.median())
print("Mode: ",dt.mode()[0])
print("Variance: ",dt.var())
print("Standard Deviation: ",dt.std())

Mean:  22.3
Median:  21.0
Mode:  15
Variance:  40.67777777777778
Standard Deviation:  6.3779132776934


In [32]:
import pandas as pd
df=pd.read_csv("robot_dataset(robot_dataset)_1.csv")
df

Robot_ID   Task_Type Component_ID     Sensor_Type            Sensor_Data  \
0    RBT_001  Inspection      CMP_460           LIDAR  1 (obstacle detected)   
1    RBT_002    Assembly      CMP_252         Thermal              85.3 (°C)   
2    RBT_003  Inspection      CMP_248         Thermal       92% (visual fit)   
3    RBT_004     Welding      CMP_433          Camera      98% (defect-free)   
4    RBT_005    Assembly      CMP_992          Camera       92% (visual fit)   
..       ...         ...          ...             ...                    ...   
495  RBT_496  Inspection      CMP_834           LIDAR              85.3 (°C)   
496  RBT_497  Inspection      CMP_851           LIDAR       92% (visual fit)   
497  RBT_498  Inspection      CMP_657           LIDAR              82.4 (°C)   
498  RBT_499    Assembly      CMP_562          Camera      98% (defect-free)   
499  RBT_500    Assembly      CMP_465  LIDAR + Camera              75.8 (°C)   

     Processing_Time (s)  Accuracy (%) Environmental_Status  \
0                   67.0          90.4               Stable   
1                   71.2          98.1               Stable   
2                   49.2          95.3             Unstable   
3                   74.5          90.2               Stable   
4                   64.5          97.2             Unstable   
..                   ...           ...                  ...   
495                 66.3          96.2             Unstable   
496                 45.1          92.8             Unstable   
497                 75.4          98.7             Unstable   
498                 48.7          94.9               Stable   
499                 73.5          91.4               Stable   

     Energy_Consumption (kWh) Human_Intervention_Needed Obstacle_Detected  \
0                         2.2                        No               Yes   
1                         2.7                       Yes                No   
2                         2.4                        No                No   
3                         2.4                       Yes                No   
4                         1.8                        No                No   
..                        ...                       ...               ...   
495                       1.3                        No               Yes   
496                       2.3                        No               Yes   
497                       2.6                       Yes                No   
498                       2.2                        No               Yes   
499                       2.0                       Yes                No   

    Defect_Detected  Interaction_Count  Steps_Walked  Objects_Recognized  \
0               Yes                  2            10                   2   
1                No                  6            23                   4   
2                No                  2            25                   3   
3               Yes                  7            34                   5   
4                No                  8            35                   3   
..              ...                ...           ...                 ...   
495              No                  4            49                   4   
496             Yes                  5            43                   8   
497              No                  6            23                   9   
498              No                  4            31                   3   
499             Yes                  5            49                   2   

     Learning_Sessions  Energy_Consumption (kWh).1  
0                   10                         100  
1                   12                         123  
2                   45                         321  
3                   12                         456  
4                   32                         654  
..                 ...                         ...  
495                 49                         130  
496                 56  

In [34]:
avg_convos = df['Interaction_Count'].mean()
print("Average (mean) number of conversations the robot has daily: ",avg_convos)

Average (mean) number of conversations the robot has daily:  5.51


In [36]:
tot_steps = df['Steps_Walked'].sum()
print("Total steps walked by the robot: ",tot_steps)

Total steps walked by the robot:  14379


In [38]:
enmax = df['Energy_Consumption (kWh)'].max()
enmin = df['Energy_Consumption (kWh)'].min()
print("Maximum energy consumption: ",enmax)
print("Minimum energy consumption: ",enmin)

Maximum energy consumption:  3.0
Minimum energy consumption:  1.0


In [42]:
swcorec= df['Steps_Walked'].corr(df['Energy_Consumption (kWh)'])
print("Correlation between the number of steps walked and energy consumption: ",swcorec)

Correlation between the number of steps walked and energy consumption:  0.0015478137393314158


In [44]:
distobjrec = df['Objects_Recognized'].describe()
print("Distribution Analysis of objects recognized daily: ",distobjrec)

Distribution Analysis of objects recognized daily:  count    500.000000
mean       4.650000
std        2.521948
min        0.000000
25%        2.750000
50%        5.000000
75%        7.000000
max        9.000000
Name: Objects_Recognized, dtype: float64


In [46]:
lsvar = df['Learning_Sessions'].var()
print("Variance in the number of learning sessions completed: ",lsvar)

Variance in the number of learning sessions completed:  391.9422845691385


In [52]:
item = "Laptop"
price = 14999.99
quantity = 20
available = True
print(f" The product is a {item}. It is priced at Rs{price} . Product is available? {available}. There are {quantity} in stock")

 The product is a Laptop. It is priced at Rs14999.99 . Product is available? True. There are 20 in stock


In [60]:
num=int(input("Enter number: "))
if num>0:
    print("It is Positive")
elif num<0:
    print("It is Negative")
else:
    print("It is Zero")

Enter number:  31


It is Positive


In [62]:
n=int(input("Enter number: "))
for i in range(1,11):
    print(n,'*',i,'=',n*i)

Enter number:  15


15 * 1 = 15
15 * 2 = 30
15 * 3 = 45
15 * 4 = 60
15 * 5 = 75
15 * 6 = 90
15 * 7 = 105
15 * 8 = 120
15 * 9 = 135
15 * 10 = 150


In [72]:
fruits = ['Apple', 'Banana', 'Orange', 'Mango', 'Strawberry','Watermelon']
# Operations
print(fruits[2])
fruits.append('Grapes')
print(fruits)
fruits.remove('Banana')
print(fruits)
fruits[4] = 'Blueberry'
print(fruits)

Orange
['Apple', 'Banana', 'Orange', 'Mango', 'Strawberry', 'Watermelon', 'Grapes']
['Apple', 'Orange', 'Mango', 'Strawberry', 'Watermelon', 'Grapes']
['Apple', 'Orange', 'Mango', 'Strawberry', 'Blueberry', 'Grapes']


In [76]:
numtup = (10, 50, 30, 40, 50)
# Operations
print(numtup[3])
print(numtup[1:4])
print(len(numtup))
print(numtup.count(50))

40
(50, 30, 40)
5
2


In [98]:
std_matmks = { 'Anne': 85, 'Belle': 90, 'Charlie': 78 }
# Operations
print(std_matmks['Belle'])
std_matmks['David'] = 92  
print(std_matmks)
std_matmks['Anne'] = 88
print(std_matmks)
del std_matmks['Charlie']
print(std_matmks)
print(std_matmks.values())
print(std_matmks.keys())

90
{'Anne': 85, 'Belle': 90, 'Charlie': 78, 'David': 92}
{'Anne': 88, 'Belle': 90, 'Charlie': 78, 'David': 92}
{'Anne': 88, 'Belle': 90, 'David': 92}
dict_values([88, 90, 92])
dict_keys(['Anne', 'Belle', 'David'])


In [82]:
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}
# Operations
union_set = set1 | set2  
print(union_set)
intersec_set = set1 & set2
print(intersec_set)
diff_set = set1 - set2 
print(diff_set)
sym_diff_set = set1 ^ set2
print(sym_diff_set)

{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5}
{1, 2, 3}
{1, 2, 3, 6, 7, 8}


In [102]:
def find_largest(numlist):
    return max(numlist)
sample_list=[24,65,97,64,52,86,32,78,57]
print("The largest number from list: ",find_largest(sample_list))

The largest number from list:  97


In [108]:
evesqnum = [x**2 for x in range(1, 21) if x % 2 == 0]
print(evesqnum)

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400]


In [116]:
product= lambda x,y: x*y
a=float(input("Enter first number: "))
b=float(input("Enter second number: "))
print("Product of the two numbers: ",product(a,b))

Enter first number:  23
Enter second number:  8


Product of the two numbers:  184.0


In [128]:
import numpy as np

arr1D = np.array([1,2,3,4,5,6,7])
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr3D = np.array([[[1, 2], [3, 4],[5, 6]], [[7, 8], [9, 10], [11, 12]]])

print(f"1D Array-\n{arr1D} \nShape: {arr1D.shape}, Dimensions: {arr1D.ndim}\n")
print(f"2D Array-\n{arr2D} \nShape: {arr2D.shape}, Dimensions: {arr2D.ndim}\n")
print(f"3D Array-\n{arr3D} \nShape: {arr3D.shape}, Dimensions: {arr3D.ndim}")

1D Array-
[1 2 3 4 5 6 7] 
Shape: (7,), Dimensions: 1

2D Array-
[[1 2 3]
 [4 5 6]
 [7 8 9]] 
Shape: (3, 3), Dimensions: 2

3D Array-
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] 
Shape: (2, 3, 2), Dimensions: 3


In [190]:
import numpy as np
array = np.random.randint(1, 101, size=(5, 5))
print(array)
# Array Indexing
ele = array[1, 2]
print(f"Element at 2nd row, 3rd column: {ele}")

[[ 73  90  18  41  16]
 [ 51  81  76  29   3]
 [  2  80  94   9  43]
 [ 96  94 100  45   6]
 [ 27   5  59  43  15]]
Element at 2nd row, 3rd column: 76


In [186]:
import numpy as np
array = np.arange(1, 17).reshape(4, 4)
print(array)
# Slicing
sr = array[1, :]
print(f"Second row: {sr}")
fc = array[:, 3]
print(f"Fourth column: {fc}")
subarr = array[2:, 1:]
print("2x3 subarray from bottom-right corner:")
print(subarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second row: [5 6 7 8]
Fourth column: [ 4  8 12 16]
2x3 subarray from bottom-right corner:
[[10 11 12]
 [14 15 16]]


In [176]:
import numpy as np
arr = np.arange(12).reshape(6, 2)
print("2D array of shape (6, 2): ",arr,sep='\n')
print("\nReshaped 3D array of shape (2, 3, 2): ",arr.reshape(2,3,2),sep='\n')
print("\nFlattened Array: ", arr.flatten(),sep='\n')

2D array of shape (6, 2): 
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

Reshaped 3D array of shape (2, 3, 2): 
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

Flattened Array: 
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [180]:
import numpy as np
arr1 = np.arange(9).reshape(3, 3)
arr2 = np.arange(3).reshape(1, 3)
res= arr1 + arr2
print("Array of shape (3,3):",arr1,"\n1D Array of shape (1,3):", arr2,"\nAfter adding using broadcasting:", res, sep='\n')

Array of shape (3,3):
[[0 1 2]
 [3 4 5]
 [6 7 8]]

1D Array of shape (1,3):
[[0 1 2]]

After adding using broadcasting:
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [198]:
import numpy as np
A= np.array([[25,78,67,92,63],[45,37,84,20,93]])
B= np.array([[56,47,24,98,76],[23,65,18,64,40]])
print("Element-wise")
print("\nAddition: ",A+B,sep='\n')
print("\nSubtraction: ",A-B,sep='\n')
print("\nMultiplication: ",A*B,sep='\n')
print("\nDivision: ",A/B,sep='\n')

Element-wise

Addition: 
[[ 81 125  91 190 139]
 [ 68 102 102  84 133]]

Subtraction: 
[[-31  31  43  -6 -13]
 [ 22 -28  66 -44  53]]

Multiplication: 
[[1400 3666 1608 9016 4788]
 [1035 2405 1512 1280 3720]]

Division: 
[[0.44642857 1.65957447 2.79166667 0.93877551 0.82894737]
 [1.95652174 0.56923077 4.66666667 0.3125     2.325     ]]


In [216]:
import pandas as pd
data = {
    'Name': ['Adrien', 'Dave', 'Monica'],
    'DA': [95, 78, 92],
    'PTRP': [88, 79, 91],
    'AI': [90, 84, 87]
}
df = pd.DataFrame(data)
df['Total'] = df[['DA', 'PTRP', 'AI']].sum(axis=1)
df['Grade'] = df['Total'].apply(lambda x: 'A' if x >= 270 else 'B' if x >= 240 else 'C' if x >= 210 else 'D')
print(df)

     Name  DA  PTRP  AI  Total Grade
0  Adrien  95    88  90    273     A
1    Dave  78    79  84    241     B
2  Monica  92    91  87    270     A
